### ISSUE TITLE
Readme structure 

### ISSUE THREAD

**Issue by medic-code** [aishwaryanr/awesome-generative-ai-guide#13]
This a great resource for all things generative AI glad I was linked to this! 

A couple of thoughts I had on the readme, please feel free to disregard though!

The announcements and explore resources at the top of the page is great.

1. Best of Gen AI papers list - its a large table at the start of the readme which I wonder whether it would be better on its own page that you provide a link on the readme
1.1 Or you could provide a way to just have the latest paper that day or week and link to the full month list elsewhere in the repo.
1.2 The abstracts could do with some spaces for easier reading, reading a block of text can be off putting. 

2. Courses section wonder whether is it worth linking to the notion site rather than individual markdown pages which has slightly better user interface (Was the plan to use the notion as the focus point of the course?)

List of free genAI courses - I know this is part of awesome guide/list modus operandi to provide as many resources as possible but I do think its is overwhelming for beginners and experts a like without context of what these resources give. I very much like the 5-10 resources of a honed in area of generative AI. I tend to find anything more than 10-15 resources per a section is just overwhelming unless there are key differentiators between resources, or particular unique ways in which things are explained.

3. Provide for each course concisely what the person is going to get out of it, i.e is it practical, theoretical and what will they be able to do afterwards. This is also speaks to not necessarily have duplicates of content (10's of beginners in LLM for example that all cover the same things) unless there is a very good reason. 

3.1 People learn in different ways, text, audio, video - I personally hate video content, the urge to skip is too high for me, but for others its great - some indication of the type of content is super useful when scrolling a list of courses.

Again amazing work!

**Comment by aishwaryanr** [comment]
@medic-code Thank you so much! Your feedback is super thoughtful :) 


1.  I have a [dedicated](https://github.com/aishwaryanr/awesome-generative-ai-guide/tree/main/research_updates) page for monthly papers, but I put it on the README as well for better visibility. I'd love to update it more often (weekly maybe), but I haven't had the time, it's something you should see soon 
     1.2 Thanks for the abstract suggestion. I'll try breaking it up for easier reading.
2. I originally started the course on Notion, but many people told me they couldn't find it with a quick Google search. That's why I copied it here too, hoping for better indexing.

3. Thanks for mentioning this concern that others have also raised. I understand where you're coming from. This might help--for beginners, I've put together a [roadmap](https://github.com/aishwaryanr/awesome-generative-ai-guide/blob/main/resources/genai_roadmap.md) of helpful courses. 

However, for this list, I intended it to be a directory of all courses, more like a news page with announcements rather than a curated list of top courses. Great point on adding more context to the course listing, honestly, I haven't had the time to go through each course thoroughly and add more details. I want to be sure that any additions I make are accurate and reliable. 


Nevertheless, these are great suggestions though, really appreciate you taking the time. I want to include them in my roadmap when I find the time to revamp this.

--Aish

**Comment by medic-code** [comment]
Hi @aishwaryanr you're welcome! Realise i don't have full context to how the repo has developed over time so super useful to get your insights into that. 

1. I presume that you're manually updating this on a monthly basis (looking at the commit history) - Maybe this is something you can call out you would like some support with ? You may not get a bite but could be a useful way to others to contribute. Also realise that there's something nice about curating this yourself though so wouldn't want to take that away from you. 

2. Ah that makes sense - I had no idea that notion was not particularly well indexed - perhaps this makes some kind of sense though. For what its worth the difference is minimal in terms of user interface, but perhaps a thought for the future if you wanted to build beyond markdown or notion. There's definitely a lot of scope and I like the reading material and linking out to other resources, this is my preferred way of learning along side projects. 

3. Yeah I can't imagine I'm the first to mention it. I think it's worth thinking on what the purpose of having a directory of all courses means to you. 

3.1 Definitely a high expectation for you personally to go through these course listing in depth, nobody has the time - but perhaps its something an open call to contribute to may be able to help support this ? Totally understand that you want it to be accurate and reliable though - this is the challenge of open source but atleast contributions can be reviewed. It's also a tough balance of providing context that is concise and useful whilst not providing huge blocks of text. 

Just FYI I really like the way you're going about course creation - reading materials + external resources + mini projects is a great combination. 

Just an additional idea but I wish there was more content on the process of knowing when AI is necessary and how to think through the approach to a project (Chip Huyen's MLOps book is a good example and Eugene Yan's content [1](https://eugeneyan.com/writing/writing-docs-why-what-how/) [2](https://eugeneyan.com/writing/ml-design-docs/). Courses to learn about a field or to do a specific thing are great but this idea focusing on the problem and evaluating where AI fits into it or not is such an important thing that gets missed. My background is in healthcare and I'm constantly thinking about this.

**Comment by aishwaryanr** [comment]
@medic-code 
Thanks so much for the great pointers on seeking community help for paper curation and course details. Scaling is definitely something I need to work on. For now, I dump paper links in a google sheet as I find them, and at the end of each month, I filter and review them. I have an LLM agent pull the PDFs, generate the markdown table, and publish it to this repo. We could definitely open the stage for others to submit PDFs once the repo gains more visibility.

Your point about explaining where generative AI might(not) be needed is also super interesting. I'm often so immersed in working with folks deeply involved in gen AI that I sometimes lose sight of how it might seem to those outside the field. This is definitely something I can create content on. 
I truly crave this kind of feedback—it's so well thought out and incredibly helpful 😄 
Please keep the suggestions coming if you have any more ideas!

**Comment by medic-code** [comment]
No worries glad to help where I can.

Sounds like you have an automated pipeline apart from finding them, filtering and reviewing the papers - tricky to automate effectively that part of the process, but community may be able to help scale this a bit again I could understand you wanting to keep this between you and a few people though for curation purposes. 

I think this strand of thinking about where gen AI might not be needed comes from a few places, one is my background is in healthcare where as 99% of people do not think about gen AI, so the mode of this type of thinking is abduntant. This is changing of course and particularly seeing more and more people being comfortable with the idea of AI in general. There are some use cases of gen AI in this space from abstract creation, to administrative tasks (we’re in the medical education and LLM space)

Additionally I think it goes beyond thinking about where gen AI is not the tool of choice,  it is also about being able to articulate clearly how does gen AI solve a problem ? This requires an understanding of the limitations, the capabilities and the perhaps with some experimentation and new discovery potential capabilities of gen AI or where are the pain points so high for humans i.e parsing millions of papers, things beyond the human mind’s capacity so that the possibility of assistance to humans becomes a opportunity for a truly interesting project or product. 

I think it’s valuable for everyone especially in the gen AI SDLC to interrogate, scrutinise and play an important influencing part in value prop design or to be able to articulate it in a design doc. To me it only enhances the type of project you want to do in gen AI to consider this stuff. For those getting started in ML it’s a bit much, but if you are a serious enthusiast and wanting to be job ready this is a really important aspect that makes people stand out from an outsiders perspective. The one way I know how to sink a gen AI product is to not solve a problem.

What’s more most of the content about this area is relatively superficial in this regard, anyone can read a list about what are gen AI’s strengths or limitations are, but perhaps people are not so aware is the data to back this up or how to articulate that effectively in relation to a specific project. 

Couple of other ideas in my mind and there’s bias here towards healthcare and those who are not involved in implementing - but I’ll throw them out there.

1. Critically appraising company’s AI and healthcare research - this is is skill set clinicians will need to get up to speed with. At the moment there are 800 devices approved by the FDA, and some small amounts Class iIb (inform clinical decision making) products in the EU so its coming whether clinicians like it or not.

2. Knowing how to make educated guesses of the type modelling you’re going to use for a particularly use case and critiquing those models. You see in the methodology of papers what they’re using, but why did they make that choice, what could they have done better ? Is an important consideration when reading the healthcare/ai literature - Again there is materials and even frameworks for this but I don’t know of many of those who are best placed to answer these questions are framing it in this way. 

3. How do effective end to end testing - I’m constantly testing a new deployed build from a clinical and QA perspective - but it always feels clumsy and not systematic - I haven’t seen so much content on this.

Perhaps an issue post may not be the best way to capture this type of information.
