### ISSUE TITLE
agent_roadmap, day1, link 2 is paywalled, need alternative

### ISSUE THREAD

**Issue by gitgoap** [aishwaryanr/awesome-generative-ai-guide#14]
# Navigating the World of LLM Agents: A Beginner’s Guide by Dominik Polzer
[This link ](https://towardsdatascience.com/navigating-the-world-of-llm-agents-a-beginners-guide-3b8d499db7a9#1336)needs a medium `subscription`. Need a similar guide but free.
![image](https://github.com/aishwaryanr/awesome-generative-ai-guide/assets/117789470/edc3ae85-17d2-4005-8384-19f01c6c68a0)

**Comment by gitgoap** [comment]
@aishwaryanr

**Comment by aishwaryanr** [comment]
@gitgoap Please feel free to read the other resource by Deepchecks, that should be good for you to proceed to the next topics.
