### ISSUE TITLE
Reading material for Day 16 forbidden

### ISSUE THREAD

**Issue by sandeepny441** [aishwaryanr/awesome-generative-ai-guide#17]
Hi, thank you for the amazing course!

Could you please post an accessible for Day 16 - Adversarial attacks. This course is nice. 

Thank you,
Sandeep

**Comment by aishwaryanr** [comment]
Thanks for pointing that out! It seems there's a redirection issue with the link. When you get redirected, it shows a '403 Forbidden' error, but if you reload the page, the content should appear
