### ISSUE TITLE
Fix numbering

### ISSUE THREAD

**Issue by birbilis** [aishwaryanr/awesome-generative-ai-guide#3]
At
https://github.com/aishwaryanr/awesome-generative-ai-guide/blob/main/free_courses/Applied_LLMs_Mastery_2024/week6_llm_evaluation.md#evaluating-retrieval-pipeline
the numbering (and indentation too probably) is wrong, all item numbers in the list stay at 1 instead of increasing

**Comment by aishwaryanr** [comment]
Thanks for pointing this out, the issue has been [fixed](https://github.com/aishwaryanr/awesome-generative-ai-guide/commit/23140f293f0186248fe6a2be9732cd083a71d083)
