### ISSUE TITLE
Add the Link of Youtube Video

### ISSUE THREAD

**Issue by dipdaiict** [aishwaryanr/awesome-generative-ai-guide#6]
Below is the Link of Introductory Video of LLM by Andrej Karpathy which contains so many info about LLM. 
Add into the Week 1 Section.

https://youtu.be/zjkBMFhNj_g?si=8h_QGe3mm0nXFvzQ

**Comment by aishwaryanr** [comment]
Thanks for the resource @dipdaiict , Upon reviewing it, the resource looks too comprehensive for week 1. I'm adding it to the course list instead.
